### ISSUE TITLE
page becomes unresponsive

### ISSUE THREAD

**Issue by lfrank** [magland/sortingview#12] opened 2021-07-06 02:09 UTC
Following the latest fixes and using version 0.2.13, the page becomes unresponsive when I click to change the magnification or try to look at timeseries.

**Comment by lfrank** [comment] 2021-07-06 02:11
And Chrome is now continuously using ~200% cpu time

**Comment by magland** [comment] 2021-07-06 02:15
Ah, okay, there was a reason I had disabled those options. Disabling for now, one minute.

**Comment by magland** [comment] 2021-07-06 02:20
I am guessing this was caused by enabling the "hide rejected" and "show accepted" options. I have disabled them for now on the GUI. Let me know if you are still experiencing that problem.

**Comment by lfrank** [comment] 2021-07-06 03:00
The new version works nicely, thanks.

It would be great to get that bug figured out and those features re-enabled, though...

**Comment by magland** [comment] 2021-07-06 11:29
In latest version (0.2.16) that functionality is restored, and the bug should be gone. Closing.

**Closed by magland** 2021-07-06 11:29 UTC
