### ISSUE TITLE
Cannot load all waveforms

### ISSUE THREAD

**Issue by acomrie** [magland/sortingview#116] opened 2021-08-12 00:34 UTC
Hello, the average waveforms for specific units are not loading, including after waiting and refreshing the page. Three of us working together have replicated this across different users/wifis. The units that don’t load are consistently the same ones across users of the same workspace. Many units load within 1 second, and the units that do not load tend to have higher unit ID numbers in this case (~100+). 

If I look at the task tracker, status says waiting,  cache hit is no, and the task remains incomplete, for tasks presumably corresponding to the waveforms not displaying. Tasks status also shows as finished for other waveform tasks with cache hit yes and a completion time, presumably for the waveforms that are correctly displaying. Any thoughts/ideas about what might be going on? Thank you!

See ex: https://sortingview.vercel.app/workspace/sorting/R-22ef22fe07c7/S-9a0fe9f61418?workspace=012153c8d1cb172e26e4220b0f9d87c2be2f44dc7e039d10abb638be5e8d44e0&channel=franklab

**Comment by magland** [comment] 2021-08-12 00:43
Thanks for the report. I think this is caused by the backend not running. Can @khl02007 check on that?

**Comment by khl02007** [comment] 2021-08-12 01:01
@magland yes the backend is not running - seems like I cannot restart it https://github.com/magland/sortingview/issues/115#issue-967554575

**Comment by acomrie** [comment] 2021-08-12 23:05
@khl02007 can you please clarify if backend is now running? We are still able to replicate this waveform loading issue across people and sortingview workspaces. Saw #117 close but not #115, so just checking if we should expect things to be loading now or not? Thanks much

**Comment by khl02007** [comment] 2021-08-12 23:32
@acomrie it's running but we found some issues with it -hopefully will get resolved tomorrow

**Comment by acomrie** [comment] 2021-08-13 17:10
I understand that this is being worked on still, so just adding updated observation that the consistent lack of loading of particular units is also occurring with autocorrelograms (not only waveform view)

**Comment by acomrie** [comment] 2021-08-16 22:50
just updating, no luck quite yet on this after some changes that I think @khl02007 was trying on Friday with the backend. On some sorts this issue is not an issue at all, while other sorts seem to have consistent waiting for particular units' waveforms and autocor plots. Could it be something sort- or unit-specific that is hanging things up?

@jsoules this is the main other "blocking" kind of lagginess I have been experiencing - seems like it may be a different underlying issue than delayed unit selection #105, and not sure if related to laggy labeling. I will be sure to take note of other ongoing processes that may be competing for computer resources while trying to load waveforms/other views with this issue moving ahead in case I can see any patterns. At the moment, I'm not seeing anything unusual via sys monitor on linux machine w/ firefox or macbook pro w/ safari or chrome while waiting for views that never complete loading. Curious if there are other things I can pay attention to that may help here, in addition to the notes above about waiting status for the related tasks. Thank you for your help!

**Comment by emilymonroe95** [comment] 2021-08-21 00:03
Hello, to give an update on this: after 10 days of the same waveforms not loading across computers, browsers, users( @acomrie ) , etc., all waveforms and correlograms/other views are now loading from original example sort. Half of the originally missing waveforms loaded about 1 hour before they all finished loading. Seems like something must have happened on the backend that allowed these to show up.

**Comment by magland** [comment] 2021-08-23 13:11
Closing because it should be covered by #120 which I have marked as high priority.

**Closed by magland** 2021-08-23 13:11 UTC
