### ISSUE TITLE
Slow to select many units

### ISSUE THREAD

**Issue by acomrie** [magland/sortingview#105] opened 2021-08-09 17:56 UTC
Have noticed this (inconsistent) behavior only when interacting with larger numbers of units at a time, for ex, when selecting 30 units in a sort with 230 total. See #10 for comments and example sortingview workspace

**Comment by magland** [comment] 2021-08-16 14:42
Example workspace: https://sortingview.vercel.app/workspace/sorting/R-c5089c48b72f/S-816a8e175985?workspace=e5c306c436a9f75fd97a20d832cd54d8243d516da53cbfe86270f11e98ee8b26&channel=franklab

**Comment by magland** [comment] 2021-08-16 14:45
@acomrie I can't reproduce any slowness in selecting units in the above workspace. Perhaps you could describe the exact steps you use? For example, which units you try to select, etc?

**Comment by jsoules** [comment] 2021-08-16 18:58
It's particularly curious that you should see slow performance in selection, because unit/row selection happens entirely client-side--in the browser, on your computer. There isn't any mechanism to write your selected row IDs to permanent storage anywhere, and the server doesn't care about it; it ought to be happening entirely in memory on your local machine.

I'm wondering, could you also share your environment? What is your OS, browser, browser version, any browser add-ons, and possibly the overall system load via TaskManager (Windows) or htop (mac/linux) etc when you experience the slowness? Is there a lot of other software running in the background that might be competing for resources?

Do you notice this specifically with a lot of other widgets/views open (such that the system would have to communicate the new selection state to several other components, like cross-correlograms or the spike amplitudes view)? I am seeing pretty much instantaneous response when I have only the units table open, but there is some lag (on the order of 250 ms?) when I've also got the spike amplitudes, average waveforms, and cross-correlograms views all open. Also, does it make a difference whether the units table view is sorted by a column other than unit ID?

Looking at the underlying selection calls, I might expect some asymmetry between select-all and deselect-all. When you click the 'select all' button, the system iterates over each row of the units table and converts the row ID (which, as part of an html element, has to be a string) to a number, then passes all the row numbers into the function that selects them; on the other hand, when you deselect all with the same button, all it has to do is replace the 'selected units' list with an empty list. That should in principle be less work. So if they're equally slow, that's kind of interesting.

On the other hand, when deselecting a single unit from a large list of units, the selection code has to create a new selection list, filtering out any single element which is part of the old selection list. This means it has to look at every selected unit. While, again, these operations *ought* to be very fast, it's still more work than deselecting everything at once, or even adding an individual unit to the selection.

At this point I'm just making guesses & speculating about how different interactions ought to perform--any information you can add about your exact setup will be very helpful.

**Comment by acomrie** [comment] 2021-08-16 22:18
Hi all, thanks, let me answer these one at a time - going with a verbose response here, so the short version is that: that the lagginess does seem inconsistent, so I'm not too surprised it wasn't replicated on your end. In fact just trying it right now, I have slowness with unit selection on my analysis computer in lab, but not with unit selection on my laptop. It may indeed all come down to what else a user is running locally simultaneously, and documenting this as we go may help reveal these patterns.

In response to Jeremy's comment - example steps I may take where unit selection can be slow to display:
1. click on link to sortingview workspace
2. open units table
3. show all units 
4. quickly try to select, say, 30+ consecutively-displayed units, one by one, perhaps with a little scrolling interspersed between the unit selections 

^This is sometimes slow all on its own, and sometimes totally fine. An alternative and more common/practical use case would be to insert steps: 3.1 reorder units table 3.2 select a subset of units 3.3 open waveform view and display all units (click show more units several times) 3.4 open autocor view and display all units (click show more units several times) 3.5 move some views to the lower panel so two views can be seen simultaneously 3.6 select all/deselect all in units table 3.7 reorder units table by another metric.... etc., then back to step 4 from above. I think this type of interaction is more representative of how we're currently using the curation tools. 

The most extreme case I have observed with the selection/deselection is relatively unusual but I have seen it enough times to be confident it can happen - that is, I'll sometimes select some units in the units table, then scroll down before those units have become highlighted, then click some more units after the scroll. And occasionally, the "wrong" units will be selected from the clicks that occurred before scrolling down - as if the computer remembered the coordinates of the click rather than the identity of the clicked unit. A little hard to describe, let me know if I should clarify.

I think @jsoules points about the system's other processes are a likely culprit. especially considering that I've found this behavior to be inconsistent. it's helpful to know the unit selection is all happening on the local machine (even if the local machine is also busy fetching waveforms from the server, etc). I have seen slowness on a work computer running linux 16.04 (🙈), firefox 88.0 without addons, and several other applications open (vscode, slack, several terminals with open port-forwarded jupyter lab sessions running on other servers, <5 other browser tabs, but no computationally intensive analysis code running in the background locally at the moment). This is where I'm currently seeing slowness right now, today, and indeed, htop/system monitor is revealing -- the big bumps in cpu history are bouts of me selecting ~10 units. I should include that I don't always observe slowness on this system, so will investigate potentially competing processes when I next have a non-laggy experience with it.

<img width="904" alt="unit_selection_sys_monitor" src="https://user-images.githubusercontent.com/46034181/129634842-ffa9ec27-7336-4500-a56f-60b06cf0423b.png">

I have also experienced slowness on my macbook pro in both safari 13.02 (no addons) and chrome 92.0.4515.131 (adobe acrobat extension) at times, but because I can't replicate it right now, I'll report back on what top/activity monitor tells me upon next observing it!

Per the usage "steps" I mentioned above, I often have had the waveform and autocor views open simultaneously, and occasionally have one other view like spike amplitude or xcor open too (but I don't have, say, 8 views open at once, usually 3 ish). Both autocor and waveform and units table views would be communicating about the selection state I think. I haven't noticed extra lag related to sorting the units table view by alternative columns. I do think that select all takes longer than deselect all usually - though I often just press the button twice and wait them all to appear deselected before moving ahead with new selections, so I wouldn't be too confident in my assessment of that without further testing/measuring. Your comments about the deselection details make sense and fit into what I've seen. 

Will keep an eye on all these factors moving forward and report back! Thanks a bunch

**Comment by acomrie** [comment] 2021-08-16 22:20
@xlsun79 @emilymonroe95, welcome to the conversation! Xulu and Emily, I know you have begun interacting with large datasets in sortingview, so can you please share info about your experiences/setups here in hopes of getting to the bottom of the lagginess we've observed? See Jeremy and Jeff's comments above with potential prompts. I know one of you  mentioned whirring laptop fans to me at some point! @rsnevers if you have a moment maybe you also have thoughts about unit selection lagginess (or lack thereof) when working with smaller datasets from tetrodes (<50 units at a time I'm guessing).  Thanks all! Really appreciate it

**Comment by rsnevers** [comment] 2021-08-17 05:52
In my experience, unit selection is generally fast except when I have the spike amplitudes tab open somewhere and am selecting units with a lot spikes (> 100000). This is especially true if I've zoomed out a lot on the spike amplitudes time axis because a lot of points are being plotted. This reliably slows down sortingview for me, and it happens even if the spike amplitude tab is open but not currently displayed.

**Comment by jsoules** [comment] 2021-08-17 17:55
@acomrie Thank you so much, this detailed response is exactly what I was looking for. When I have the average waveforms and autocorrelograms views open & have clicked to show everything, I too am having some noticeable lag issues.

In case you're curious, the short story is something along these lines: we share a selection state among all the views & apply styling (highlights) to the visualizations based on the selection state. When the selections in the units table change, that causes the system re-render everything in the other open views. They're supposed to be cached and updated only if they've actually changed, but that doesn't seem to be happening. Even more unfortunately, that "getting redrawn" thing applies whether they're actually on screen or not. (i.e. I think @rsnevers is spot-on about plotting a lot of points.) The biggest thing I'm seeing in the profiler is a load time of between 4 and 10 ms for each average waveform view. That doesn't seem like much, but with 226 units, it's easily over a second by itself, even if they were all on the lower end of that range.

I'm trying to zero in on exactly what calls are resulting in these excessive load times; unfortunately, the load keeps causing my profiler to lock up and crash. I will continue looking into it and update here as I make progress.

In the mean time, please feel free to keep updating these tickets with details of any further performance issues. Once again, the level of detail above is extremely helpful.

**Comment by emilymonroe95** [comment] 2021-08-21 00:38
I have experienced some slowness as well. For context, it mostly happens on the first time (at least) opening up a given spike sort, but occurs across computers, browsers, and number of applications open on the computer. I had more slowness using safari than chrome, especially with other windows/tabs open.

My order of operations would be: first click on the link to open sortingview, then open up the units table. Selecting units occurs at normal speed at this point. If I then open up the waveforms view and try to select units, it is somewhat laggy (take an extra second to select). Its also slow to purely select the units in the spike amplitudes view and for the cross correlograms, but even longer to load their output, especially the first time loading them. 

The slowness in selecting units in the units table decreases after closing the average waveforms view, and also over time that the sort is open (better after ~10min).

It seems to me that after things have loaded once from the initial opening of a sort on a computer, they load more quickly and slowness/lagging mostly goes away on future openings of the same sort.

I experienced the “whirring” fans on my laptop the first couple of times I ever opened a sort. I was using safari with a few other windows/applications open. The sort had ~230 units and I was exploring the different views (e.g. clicking on units while loading waveforms), but I haven’t experienced this issue since (even with opening other new sorts). 

Thanks all!

**Comment by acomrie** [comment] 2021-08-23 16:03
@magland, you may have already seen this, just looping you in here in case you hadn't followed the conversation - wanted to add that other than the kachery memory overloading issue, this is the main other issue that is relatively high priority on the user end in my opinion. Seems like @jsoules is on it and has some ideas :) Thanks both!

**Comment by acomrie** [comment] 2021-09-01 00:15
Hi all, gave this a go today along with @emilymonroe95 and @xlsun79. The unit selection is definitely way more responsive! This makes manual curation significantly more user-friendly. We also thought that the displays that change their highlighting based on unit table selection seemed to load faster (i.e., waevforms and autocor). Label-adding seemed faster but still occasionally got backed up (perhaps after adding 10 labels one unit at a time, a page refresh and reopening the views could fix this). The spike amplitudes view still took longest to interact with, but it's a ton of data to load especially when there are many spikes, so it's certainly understandable. Overall, this is a great improvement in my opinion, with a couple potential areas for any future work on performance (label adding becoming laggy over time and the general slowness of data-heavy spike amplitudes view). Thanks Jeff and Jeremy!

**Comment by jsoules** [comment] 2021-09-01 13:57
@acomrie Thanks for your feedback--glad to hear things are much improved. Units table, waveforms, and autocorrelograms were exactly the areas I dug into, so if you're noticing them working faster, that's a big win. (No surprise that labels and spike amplitudes did not see much improvement--I didn't make any changes there, so they'd just be benefiting as a secondary effect of the units table improvement.)

Regarding the performance of labels and spike amplitudes, in those cases I suspect there may be a bigger contribution from the way the system back-end works than there was for the units table & selectable unit views. To avoid scope creep on this issue, could I ask that you open a new issue or two if you'd like us to look into those more? I'd otherwise close this issue out.

**Comment by acomrie** [comment] 2021-09-01 16:07
Sure, sounds good to go ahead and close. Thanks!

**Closed** 2021-09-01 18:13 UTC
